spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${URL}
    username: ${USERNAME}
    password: ${PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      show_sql: true

  redis:
    host: localhost
    port: 6379

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL}
    password: ${EMAIL-PASSWORD}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

  jackson:
    property-naming-strategy : SNAKE_CASE

jwt :
  key : ${JWT_KEY}
  live :
    accessTokenTimeMillis : ${ACCESS_TOKEN_TIME}
    refreshTokenTimeMillis : ${REFRESH_TOKEN_TIME}
